# 設問2の解答

## 環境

Python 3.6.9
pytest == 6.2.3

## 追加の仮定

初めてN回連続でタイムアウトしたとき，その時刻を故障した時間とみなす．

## テストの内容

`surveilance_q2_01.csv`

1つのサーバが一回だけping応答に失敗する場合のログ

`surveilance_q2_02.csv`

サーバ`10.20.30.1/16`が最大1回連続でpingに対してタイムアウトし，サーバ`10.20.30.1/16`が最大2回連続でpingに対しタイムアウトする場合のログ

`surveilance_q2_03.csv`

どのサーバもping応答に失敗しない場合のログ

## テストの結果

6 passed
